# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .authentication_settings import *
from .certificate import *
from .consumer import *
from .consumer_acl import *
from .consumer_basic import *
from .consumer_hmac import *
from .consumer_jwt import *
from .consumer_key import *
from .control_plane import *
from .dp_certificate import *
from .get_consumer import *
from .get_control_plane import *
from .get_nodes import *
from .get_role import *
from .get_team import *
from .get_team_role import *
from .get_user import *
from .get_user_role import *
from .identity_provider import *
from .plugin import *
from .provider import *
from .route import *
from .service import *
from .team import *
from .team_mappings import *
from .team_role import *
from .team_user import *
from .user import *
from .user_role import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_konnect.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_konnect.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "konnect",
  "mod": "index/authenticationSettings",
  "fqn": "pulumi_konnect",
  "classes": {
   "konnect:index/authenticationSettings:AuthenticationSettings": "AuthenticationSettings"
  }
 },
 {
  "pkg": "konnect",
  "mod": "index/certificate",
  "fqn": "pulumi_konnect",
  "classes": {
   "konnect:index/certificate:Certificate": "Certificate"
  }
 },
 {
  "pkg": "konnect",
  "mod": "index/consumer",
  "fqn": "pulumi_konnect",
  "classes": {
   "konnect:index/consumer:Consumer": "Consumer"
  }
 },
 {
  "pkg": "konnect",
  "mod": "index/consumerACL",
  "fqn": "pulumi_konnect",
  "classes": {
   "konnect:index/consumerACL:ConsumerACL": "ConsumerACL"
  }
 },
 {
  "pkg": "konnect",
  "mod": "index/consumerBasic",
  "fqn": "pulumi_konnect",
  "classes": {
   "konnect:index/consumerBasic:ConsumerBasic": "ConsumerBasic"
  }
 },
 {
  "pkg": "konnect",
  "mod": "index/consumerHMAC",
  "fqn": "pulumi_konnect",
  "classes": {
   "konnect:index/consumerHMAC:ConsumerHMAC": "ConsumerHMAC"
  }
 },
 {
  "pkg": "konnect",
  "mod": "index/consumerJWT",
  "fqn": "pulumi_konnect",
  "classes": {
   "konnect:index/consumerJWT:ConsumerJWT": "ConsumerJWT"
  }
 },
 {
  "pkg": "konnect",
  "mod": "index/consumerKey",
  "fqn": "pulumi_konnect",
  "classes": {
   "konnect:index/consumerKey:ConsumerKey": "ConsumerKey"
  }
 },
 {
  "pkg": "konnect",
  "mod": "index/controlPlane",
  "fqn": "pulumi_konnect",
  "classes": {
   "konnect:index/controlPlane:ControlPlane": "ControlPlane"
  }
 },
 {
  "pkg": "konnect",
  "mod": "index/dpCertificate",
  "fqn": "pulumi_konnect",
  "classes": {
   "konnect:index/dpCertificate:DpCertificate": "DpCertificate"
  }
 },
 {
  "pkg": "konnect",
  "mod": "index/identityProvider",
  "fqn": "pulumi_konnect",
  "classes": {
   "konnect:index/identityProvider:IdentityProvider": "IdentityProvider"
  }
 },
 {
  "pkg": "konnect",
  "mod": "index/plugin",
  "fqn": "pulumi_konnect",
  "classes": {
   "konnect:index/plugin:Plugin": "Plugin"
  }
 },
 {
  "pkg": "konnect",
  "mod": "index/route",
  "fqn": "pulumi_konnect",
  "classes": {
   "konnect:index/route:Route": "Route"
  }
 },
 {
  "pkg": "konnect",
  "mod": "index/service",
  "fqn": "pulumi_konnect",
  "classes": {
   "konnect:index/service:Service": "Service"
  }
 },
 {
  "pkg": "konnect",
  "mod": "index/team",
  "fqn": "pulumi_konnect",
  "classes": {
   "konnect:index/team:Team": "Team"
  }
 },
 {
  "pkg": "konnect",
  "mod": "index/teamMappings",
  "fqn": "pulumi_konnect",
  "classes": {
   "konnect:index/teamMappings:TeamMappings": "TeamMappings"
  }
 },
 {
  "pkg": "konnect",
  "mod": "index/teamRole",
  "fqn": "pulumi_konnect",
  "classes": {
   "konnect:index/teamRole:TeamRole": "TeamRole"
  }
 },
 {
  "pkg": "konnect",
  "mod": "index/teamUser",
  "fqn": "pulumi_konnect",
  "classes": {
   "konnect:index/teamUser:TeamUser": "TeamUser"
  }
 },
 {
  "pkg": "konnect",
  "mod": "index/user",
  "fqn": "pulumi_konnect",
  "classes": {
   "konnect:index/user:User": "User"
  }
 },
 {
  "pkg": "konnect",
  "mod": "index/userRole",
  "fqn": "pulumi_konnect",
  "classes": {
   "konnect:index/userRole:UserRole": "UserRole"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "konnect",
  "token": "pulumi:providers:konnect",
  "fqn": "pulumi_konnect",
  "class": "Provider"
 }
]
"""
)
