# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities

__all__ = ['CertificateArgs', 'Certificate']

@pulumi.input_type
class CertificateArgs:
    def __init__(__self__, *,
                 certificate: pulumi.Input[str],
                 control_plane_id: pulumi.Input[str],
                 key: pulumi.Input[str],
                 alternate_certificate: Optional[pulumi.Input[str]] = None,
                 alternate_key: Optional[pulumi.Input[str]] = None):
        """
        The set of arguments for constructing a Certificate resource.
        """
        pulumi.set(__self__, "certificate", certificate)
        pulumi.set(__self__, "control_plane_id", control_plane_id)
        pulumi.set(__self__, "key", key)
        if alternate_certificate is not None:
            pulumi.set(__self__, "alternate_certificate", alternate_certificate)
        if alternate_key is not None:
            pulumi.set(__self__, "alternate_key", alternate_key)

    @property
    @pulumi.getter
    def certificate(self) -> pulumi.Input[str]:
        return pulumi.get(self, "certificate")

    @certificate.setter
    def certificate(self, value: pulumi.Input[str]):
        pulumi.set(self, "certificate", value)

    @property
    @pulumi.getter(name="controlPlaneId")
    def control_plane_id(self) -> pulumi.Input[str]:
        return pulumi.get(self, "control_plane_id")

    @control_plane_id.setter
    def control_plane_id(self, value: pulumi.Input[str]):
        pulumi.set(self, "control_plane_id", value)

    @property
    @pulumi.getter
    def key(self) -> pulumi.Input[str]:
        return pulumi.get(self, "key")

    @key.setter
    def key(self, value: pulumi.Input[str]):
        pulumi.set(self, "key", value)

    @property
    @pulumi.getter(name="alternateCertificate")
    def alternate_certificate(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "alternate_certificate")

    @alternate_certificate.setter
    def alternate_certificate(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "alternate_certificate", value)

    @property
    @pulumi.getter(name="alternateKey")
    def alternate_key(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "alternate_key")

    @alternate_key.setter
    def alternate_key(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "alternate_key", value)


@pulumi.input_type
class _CertificateState:
    def __init__(__self__, *,
                 alternate_certificate: Optional[pulumi.Input[str]] = None,
                 alternate_key: Optional[pulumi.Input[str]] = None,
                 certificate: Optional[pulumi.Input[str]] = None,
                 control_plane_id: Optional[pulumi.Input[str]] = None,
                 key: Optional[pulumi.Input[str]] = None):
        """
        Input properties used for looking up and filtering Certificate resources.
        """
        if alternate_certificate is not None:
            pulumi.set(__self__, "alternate_certificate", alternate_certificate)
        if alternate_key is not None:
            pulumi.set(__self__, "alternate_key", alternate_key)
        if certificate is not None:
            pulumi.set(__self__, "certificate", certificate)
        if control_plane_id is not None:
            pulumi.set(__self__, "control_plane_id", control_plane_id)
        if key is not None:
            pulumi.set(__self__, "key", key)

    @property
    @pulumi.getter(name="alternateCertificate")
    def alternate_certificate(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "alternate_certificate")

    @alternate_certificate.setter
    def alternate_certificate(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "alternate_certificate", value)

    @property
    @pulumi.getter(name="alternateKey")
    def alternate_key(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "alternate_key")

    @alternate_key.setter
    def alternate_key(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "alternate_key", value)

    @property
    @pulumi.getter
    def certificate(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "certificate")

    @certificate.setter
    def certificate(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "certificate", value)

    @property
    @pulumi.getter(name="controlPlaneId")
    def control_plane_id(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "control_plane_id")

    @control_plane_id.setter
    def control_plane_id(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "control_plane_id", value)

    @property
    @pulumi.getter
    def key(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "key")

    @key.setter
    def key(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "key", value)


class Certificate(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 alternate_certificate: Optional[pulumi.Input[str]] = None,
                 alternate_key: Optional[pulumi.Input[str]] = None,
                 certificate: Optional[pulumi.Input[str]] = None,
                 control_plane_id: Optional[pulumi.Input[str]] = None,
                 key: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        """
        Create a Certificate resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: CertificateArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a Certificate resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param CertificateArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(CertificateArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 alternate_certificate: Optional[pulumi.Input[str]] = None,
                 alternate_key: Optional[pulumi.Input[str]] = None,
                 certificate: Optional[pulumi.Input[str]] = None,
                 control_plane_id: Optional[pulumi.Input[str]] = None,
                 key: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = CertificateArgs.__new__(CertificateArgs)

            __props__.__dict__["alternate_certificate"] = alternate_certificate
            __props__.__dict__["alternate_key"] = alternate_key
            if certificate is None and not opts.urn:
                raise TypeError("Missing required property 'certificate'")
            __props__.__dict__["certificate"] = certificate
            if control_plane_id is None and not opts.urn:
                raise TypeError("Missing required property 'control_plane_id'")
            __props__.__dict__["control_plane_id"] = control_plane_id
            if key is None and not opts.urn:
                raise TypeError("Missing required property 'key'")
            __props__.__dict__["key"] = key
        super(Certificate, __self__).__init__(
            'konnect:index/certificate:Certificate',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            alternate_certificate: Optional[pulumi.Input[str]] = None,
            alternate_key: Optional[pulumi.Input[str]] = None,
            certificate: Optional[pulumi.Input[str]] = None,
            control_plane_id: Optional[pulumi.Input[str]] = None,
            key: Optional[pulumi.Input[str]] = None) -> 'Certificate':
        """
        Get an existing Certificate resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _CertificateState.__new__(_CertificateState)

        __props__.__dict__["alternate_certificate"] = alternate_certificate
        __props__.__dict__["alternate_key"] = alternate_key
        __props__.__dict__["certificate"] = certificate
        __props__.__dict__["control_plane_id"] = control_plane_id
        __props__.__dict__["key"] = key
        return Certificate(resource_name, opts=opts, __props__=__props__)

    @property
    @pulumi.getter(name="alternateCertificate")
    def alternate_certificate(self) -> pulumi.Output[Optional[str]]:
        return pulumi.get(self, "alternate_certificate")

    @property
    @pulumi.getter(name="alternateKey")
    def alternate_key(self) -> pulumi.Output[Optional[str]]:
        return pulumi.get(self, "alternate_key")

    @property
    @pulumi.getter
    def certificate(self) -> pulumi.Output[str]:
        return pulumi.get(self, "certificate")

    @property
    @pulumi.getter(name="controlPlaneId")
    def control_plane_id(self) -> pulumi.Output[str]:
        return pulumi.get(self, "control_plane_id")

    @property
    @pulumi.getter
    def key(self) -> pulumi.Output[str]:
        return pulumi.get(self, "key")

