# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities

__all__ = ['ConsumerKeyArgs', 'ConsumerKey']

@pulumi.input_type
class ConsumerKeyArgs:
    def __init__(__self__, *,
                 consumer_id: pulumi.Input[str],
                 control_plane_id: pulumi.Input[str],
                 key: Optional[pulumi.Input[str]] = None):
        """
        The set of arguments for constructing a ConsumerKey resource.
        :param pulumi.Input[str] consumer_id: **(Required, String)** The id of the consumer.
        :param pulumi.Input[str] control_plane_id: **(Required, String)** The id of the control plane.
        :param pulumi.Input[str] key: **(Optional/Computed, String)** The API key value.  If left out, a key will be generated for you.
        """
        pulumi.set(__self__, "consumer_id", consumer_id)
        pulumi.set(__self__, "control_plane_id", control_plane_id)
        if key is not None:
            pulumi.set(__self__, "key", key)

    @property
    @pulumi.getter(name="consumerId")
    def consumer_id(self) -> pulumi.Input[str]:
        """
        **(Required, String)** The id of the consumer.
        """
        return pulumi.get(self, "consumer_id")

    @consumer_id.setter
    def consumer_id(self, value: pulumi.Input[str]):
        pulumi.set(self, "consumer_id", value)

    @property
    @pulumi.getter(name="controlPlaneId")
    def control_plane_id(self) -> pulumi.Input[str]:
        """
        **(Required, String)** The id of the control plane.
        """
        return pulumi.get(self, "control_plane_id")

    @control_plane_id.setter
    def control_plane_id(self, value: pulumi.Input[str]):
        pulumi.set(self, "control_plane_id", value)

    @property
    @pulumi.getter
    def key(self) -> Optional[pulumi.Input[str]]:
        """
        **(Optional/Computed, String)** The API key value.  If left out, a key will be generated for you.
        """
        return pulumi.get(self, "key")

    @key.setter
    def key(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "key", value)


@pulumi.input_type
class _ConsumerKeyState:
    def __init__(__self__, *,
                 consumer_id: Optional[pulumi.Input[str]] = None,
                 control_plane_id: Optional[pulumi.Input[str]] = None,
                 key: Optional[pulumi.Input[str]] = None,
                 key_id: Optional[pulumi.Input[str]] = None):
        """
        Input properties used for looking up and filtering ConsumerKey resources.
        :param pulumi.Input[str] consumer_id: **(Required, String)** The id of the consumer.
        :param pulumi.Input[str] control_plane_id: **(Required, String)** The id of the control plane.
        :param pulumi.Input[str] key: **(Optional/Computed, String)** The API key value.  If left out, a key will be generated for you.
        :param pulumi.Input[str] key_id: **(String)** Id of the consumer API key alone
        """
        if consumer_id is not None:
            pulumi.set(__self__, "consumer_id", consumer_id)
        if control_plane_id is not None:
            pulumi.set(__self__, "control_plane_id", control_plane_id)
        if key is not None:
            pulumi.set(__self__, "key", key)
        if key_id is not None:
            pulumi.set(__self__, "key_id", key_id)

    @property
    @pulumi.getter(name="consumerId")
    def consumer_id(self) -> Optional[pulumi.Input[str]]:
        """
        **(Required, String)** The id of the consumer.
        """
        return pulumi.get(self, "consumer_id")

    @consumer_id.setter
    def consumer_id(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "consumer_id", value)

    @property
    @pulumi.getter(name="controlPlaneId")
    def control_plane_id(self) -> Optional[pulumi.Input[str]]:
        """
        **(Required, String)** The id of the control plane.
        """
        return pulumi.get(self, "control_plane_id")

    @control_plane_id.setter
    def control_plane_id(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "control_plane_id", value)

    @property
    @pulumi.getter
    def key(self) -> Optional[pulumi.Input[str]]:
        """
        **(Optional/Computed, String)** The API key value.  If left out, a key will be generated for you.
        """
        return pulumi.get(self, "key")

    @key.setter
    def key(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "key", value)

    @property
    @pulumi.getter(name="keyId")
    def key_id(self) -> Optional[pulumi.Input[str]]:
        """
        **(String)** Id of the consumer API key alone
        """
        return pulumi.get(self, "key_id")

    @key_id.setter
    def key_id(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "key_id", value)


class ConsumerKey(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 consumer_id: Optional[pulumi.Input[str]] = None,
                 control_plane_id: Optional[pulumi.Input[str]] = None,
                 key: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        """
        Represents an API key credential for a consumer within a control plane
        ## Example Usage

        ```python
        import pulumi
        import pulumi_konnect as konnect

        control_plane = konnect.get_control_plane(name="TestControlPlane")
        consumer = konnect.get_consumer(control_plane_id=control_plane.id,
            search_username="Bob")
        example = konnect.ConsumerKey("example",
            control_plane_id=control_plane.id,
            consumer_id=consumer.consumer_id,
            key="my-api-key")
        ```

        ## Import

        Consumer keys can be imported using a proper value of `id` as described above

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[str] consumer_id: **(Required, String)** The id of the consumer.
        :param pulumi.Input[str] control_plane_id: **(Required, String)** The id of the control plane.
        :param pulumi.Input[str] key: **(Optional/Computed, String)** The API key value.  If left out, a key will be generated for you.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: ConsumerKeyArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Represents an API key credential for a consumer within a control plane
        ## Example Usage

        ```python
        import pulumi
        import pulumi_konnect as konnect

        control_plane = konnect.get_control_plane(name="TestControlPlane")
        consumer = konnect.get_consumer(control_plane_id=control_plane.id,
            search_username="Bob")
        example = konnect.ConsumerKey("example",
            control_plane_id=control_plane.id,
            consumer_id=consumer.consumer_id,
            key="my-api-key")
        ```

        ## Import

        Consumer keys can be imported using a proper value of `id` as described above

        :param str resource_name: The name of the resource.
        :param ConsumerKeyArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ConsumerKeyArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 consumer_id: Optional[pulumi.Input[str]] = None,
                 control_plane_id: Optional[pulumi.Input[str]] = None,
                 key: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ConsumerKeyArgs.__new__(ConsumerKeyArgs)

            if consumer_id is None and not opts.urn:
                raise TypeError("Missing required property 'consumer_id'")
            __props__.__dict__["consumer_id"] = consumer_id
            if control_plane_id is None and not opts.urn:
                raise TypeError("Missing required property 'control_plane_id'")
            __props__.__dict__["control_plane_id"] = control_plane_id
            __props__.__dict__["key"] = key
            __props__.__dict__["key_id"] = None
        super(ConsumerKey, __self__).__init__(
            'konnect:index/consumerKey:ConsumerKey',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            consumer_id: Optional[pulumi.Input[str]] = None,
            control_plane_id: Optional[pulumi.Input[str]] = None,
            key: Optional[pulumi.Input[str]] = None,
            key_id: Optional[pulumi.Input[str]] = None) -> 'ConsumerKey':
        """
        Get an existing ConsumerKey resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[str] consumer_id: **(Required, String)** The id of the consumer.
        :param pulumi.Input[str] control_plane_id: **(Required, String)** The id of the control plane.
        :param pulumi.Input[str] key: **(Optional/Computed, String)** The API key value.  If left out, a key will be generated for you.
        :param pulumi.Input[str] key_id: **(String)** Id of the consumer API key alone
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _ConsumerKeyState.__new__(_ConsumerKeyState)

        __props__.__dict__["consumer_id"] = consumer_id
        __props__.__dict__["control_plane_id"] = control_plane_id
        __props__.__dict__["key"] = key
        __props__.__dict__["key_id"] = key_id
        return ConsumerKey(resource_name, opts=opts, __props__=__props__)

    @property
    @pulumi.getter(name="consumerId")
    def consumer_id(self) -> pulumi.Output[str]:
        """
        **(Required, String)** The id of the consumer.
        """
        return pulumi.get(self, "consumer_id")

    @property
    @pulumi.getter(name="controlPlaneId")
    def control_plane_id(self) -> pulumi.Output[str]:
        """
        **(Required, String)** The id of the control plane.
        """
        return pulumi.get(self, "control_plane_id")

    @property
    @pulumi.getter
    def key(self) -> pulumi.Output[str]:
        """
        **(Optional/Computed, String)** The API key value.  If left out, a key will be generated for you.
        """
        return pulumi.get(self, "key")

    @property
    @pulumi.getter(name="keyId")
    def key_id(self) -> pulumi.Output[str]:
        """
        **(String)** Id of the consumer API key alone
        """
        return pulumi.get(self, "key_id")

