// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Konnect
{
    /// <summary>
    /// Represents a JWT credential for a consumer within a control plane
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Konnect = Pulumi.Konnect;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var controlPlane = Konnect.GetControlPlane.Invoke(new()
    ///     {
    ///         Name = "TestControlPlane",
    ///     });
    /// 
    ///     var consumer = Konnect.GetConsumer.Invoke(new()
    ///     {
    ///         ControlPlaneId = controlPlane.Apply(getControlPlaneResult =&gt; getControlPlaneResult.Id),
    ///         SearchUsername = "Bob",
    ///     });
    /// 
    ///     var example = new Konnect.ConsumerJWT("example", new()
    ///     {
    ///         ControlPlaneId = controlPlane.Apply(getControlPlaneResult =&gt; getControlPlaneResult.Id),
    ///         ConsumerId = consumer.Apply(getConsumerResult =&gt; getConsumerResult.ConsumerId),
    ///         Key = "my-key",
    ///         Secret = "my-secret",
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// Consumer JWTs can be imported using a proper value of `id` as described above
    /// </summary>
    [KonnectResourceType("konnect:index/consumerJWT:ConsumerJWT")]
    public partial class ConsumerJWT : global::Pulumi.CustomResource
    {
        /// <summary>
        /// **(Optional, String)** The algorithm for the JWT.  Allowed values: `HS256`, `HS384`, `HS512`, `RS256`, `RS384`, `RS512`, `ES256`, `ES384`. Default: `HS256`
        /// </summary>
        [Output("algorithm")]
        public Output<string?> Algorithm { get; private set; } = null!;

        /// <summary>
        /// **(Required, String)** The id of the consumer.
        /// </summary>
        [Output("consumerId")]
        public Output<string> ConsumerId { get; private set; } = null!;

        /// <summary>
        /// **(Required, String)** The id of the control plane.
        /// </summary>
        [Output("controlPlaneId")]
        public Output<string> ControlPlaneId { get; private set; } = null!;

        /// <summary>
        /// **(String)** Id of the consumer JWT alone
        /// </summary>
        [Output("jwtId")]
        public Output<string> JwtId { get; private set; } = null!;

        /// <summary>
        /// **(Optional/Computed, String)** The key value.  If left out, a key will be generated for you.
        /// </summary>
        [Output("key")]
        public Output<string> Key { get; private set; } = null!;

        /// <summary>
        /// **(Optional, String)** The RSA public key in PEM format for the JWT.  Required if `algorithm` is `RS256`, `RS384`, `RS512`, `ES256`, or `ES384`.
        /// </summary>
        [Output("rsaPublicKey")]
        public Output<string?> RsaPublicKey { get; private set; } = null!;

        /// <summary>
        /// **(Optional/Computed, String)** The secret value.  If left out, a key will be generated for you.
        /// </summary>
        [Output("secret")]
        public Output<string> Secret { get; private set; } = null!;


        /// <summary>
        /// Create a ConsumerJWT resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ConsumerJWT(string name, ConsumerJWTArgs args, CustomResourceOptions? options = null)
            : base("konnect:index/consumerJWT:ConsumerJWT", name, args ?? new ConsumerJWTArgs(), MakeResourceOptions(options, ""))
        {
        }

        private ConsumerJWT(string name, Input<string> id, ConsumerJWTState? state = null, CustomResourceOptions? options = null)
            : base("konnect:index/consumerJWT:ConsumerJWT", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing ConsumerJWT resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static ConsumerJWT Get(string name, Input<string> id, ConsumerJWTState? state = null, CustomResourceOptions? options = null)
        {
            return new ConsumerJWT(name, id, state, options);
        }
    }

    public sealed class ConsumerJWTArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// **(Optional, String)** The algorithm for the JWT.  Allowed values: `HS256`, `HS384`, `HS512`, `RS256`, `RS384`, `RS512`, `ES256`, `ES384`. Default: `HS256`
        /// </summary>
        [Input("algorithm")]
        public Input<string>? Algorithm { get; set; }

        /// <summary>
        /// **(Required, String)** The id of the consumer.
        /// </summary>
        [Input("consumerId", required: true)]
        public Input<string> ConsumerId { get; set; } = null!;

        /// <summary>
        /// **(Required, String)** The id of the control plane.
        /// </summary>
        [Input("controlPlaneId", required: true)]
        public Input<string> ControlPlaneId { get; set; } = null!;

        /// <summary>
        /// **(Optional/Computed, String)** The key value.  If left out, a key will be generated for you.
        /// </summary>
        [Input("key")]
        public Input<string>? Key { get; set; }

        /// <summary>
        /// **(Optional, String)** The RSA public key in PEM format for the JWT.  Required if `algorithm` is `RS256`, `RS384`, `RS512`, `ES256`, or `ES384`.
        /// </summary>
        [Input("rsaPublicKey")]
        public Input<string>? RsaPublicKey { get; set; }

        /// <summary>
        /// **(Optional/Computed, String)** The secret value.  If left out, a key will be generated for you.
        /// </summary>
        [Input("secret")]
        public Input<string>? Secret { get; set; }

        public ConsumerJWTArgs()
        {
        }
        public static new ConsumerJWTArgs Empty => new ConsumerJWTArgs();
    }

    public sealed class ConsumerJWTState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// **(Optional, String)** The algorithm for the JWT.  Allowed values: `HS256`, `HS384`, `HS512`, `RS256`, `RS384`, `RS512`, `ES256`, `ES384`. Default: `HS256`
        /// </summary>
        [Input("algorithm")]
        public Input<string>? Algorithm { get; set; }

        /// <summary>
        /// **(Required, String)** The id of the consumer.
        /// </summary>
        [Input("consumerId")]
        public Input<string>? ConsumerId { get; set; }

        /// <summary>
        /// **(Required, String)** The id of the control plane.
        /// </summary>
        [Input("controlPlaneId")]
        public Input<string>? ControlPlaneId { get; set; }

        /// <summary>
        /// **(String)** Id of the consumer JWT alone
        /// </summary>
        [Input("jwtId")]
        public Input<string>? JwtId { get; set; }

        /// <summary>
        /// **(Optional/Computed, String)** The key value.  If left out, a key will be generated for you.
        /// </summary>
        [Input("key")]
        public Input<string>? Key { get; set; }

        /// <summary>
        /// **(Optional, String)** The RSA public key in PEM format for the JWT.  Required if `algorithm` is `RS256`, `RS384`, `RS512`, `ES256`, or `ES384`.
        /// </summary>
        [Input("rsaPublicKey")]
        public Input<string>? RsaPublicKey { get; set; }

        /// <summary>
        /// **(Optional/Computed, String)** The secret value.  If left out, a key will be generated for you.
        /// </summary>
        [Input("secret")]
        public Input<string>? Secret { get; set; }

        public ConsumerJWTState()
        {
        }
        public static new ConsumerJWTState Empty => new ConsumerJWTState();
    }
}
