// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Konnect
{
    /// <summary>
    /// Represents a control plane
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Konnect = Pulumi.Konnect;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var example = new Konnect.ControlPlane("example", new()
    ///     {
    ///         Description = "TestControlPlane",
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// Control planes can be imported using a proper value of `id` as described above
    /// </summary>
    [KonnectResourceType("konnect:index/controlPlane:ControlPlane")]
    public partial class ControlPlane : global::Pulumi.CustomResource
    {
        /// <summary>
        /// **(String)** The cluster type of the control plane.
        /// </summary>
        [Output("clusterType")]
        public Output<string> ClusterType { get; private set; } = null!;

        /// <summary>
        /// **(String)** The control plane endpoint URL of the control plane.
        /// </summary>
        [Output("controlPlaneEndpoint")]
        public Output<string> ControlPlaneEndpoint { get; private set; } = null!;

        /// <summary>
        /// **(Optional, String)** The description of the control plane.
        /// </summary>
        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        /// <summary>
        /// **(Required, String)** The name of the control plane.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// **(String)** The telemetry endpoint URL of the control plane.
        /// </summary>
        [Output("telemetryEndpoint")]
        public Output<string> TelemetryEndpoint { get; private set; } = null!;


        /// <summary>
        /// Create a ControlPlane resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ControlPlane(string name, ControlPlaneArgs? args = null, CustomResourceOptions? options = null)
            : base("konnect:index/controlPlane:ControlPlane", name, args ?? new ControlPlaneArgs(), MakeResourceOptions(options, ""))
        {
        }

        private ControlPlane(string name, Input<string> id, ControlPlaneState? state = null, CustomResourceOptions? options = null)
            : base("konnect:index/controlPlane:ControlPlane", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/csechrist/pulumi-konnect",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing ControlPlane resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static ControlPlane Get(string name, Input<string> id, ControlPlaneState? state = null, CustomResourceOptions? options = null)
        {
            return new ControlPlane(name, id, state, options);
        }
    }

    public sealed class ControlPlaneArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// **(Optional, String)** The description of the control plane.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// **(Required, String)** The name of the control plane.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        public ControlPlaneArgs()
        {
        }
        public static new ControlPlaneArgs Empty => new ControlPlaneArgs();
    }

    public sealed class ControlPlaneState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// **(String)** The cluster type of the control plane.
        /// </summary>
        [Input("clusterType")]
        public Input<string>? ClusterType { get; set; }

        /// <summary>
        /// **(String)** The control plane endpoint URL of the control plane.
        /// </summary>
        [Input("controlPlaneEndpoint")]
        public Input<string>? ControlPlaneEndpoint { get; set; }

        /// <summary>
        /// **(Optional, String)** The description of the control plane.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// **(Required, String)** The name of the control plane.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// **(String)** The telemetry endpoint URL of the control plane.
        /// </summary>
        [Input("telemetryEndpoint")]
        public Input<string>? TelemetryEndpoint { get; set; }

        public ControlPlaneState()
        {
        }
        public static new ControlPlaneState Empty => new ControlPlaneState();
    }
}
