// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Konnect
{
    public static class GetControlPlane
    {
        /// <summary>
        /// Represents a control plane
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Konnect = Pulumi.Konnect;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var example = Konnect.GetControlPlane.Invoke(new()
        ///     {
        ///         Name = "TestControlPlane",
        ///     });
        /// 
        /// });
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Task<GetControlPlaneResult> InvokeAsync(GetControlPlaneArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetControlPlaneResult>("konnect:index/getControlPlane:getControlPlane", args ?? new GetControlPlaneArgs(), options.WithDefaults());

        /// <summary>
        /// Represents a control plane
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Konnect = Pulumi.Konnect;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var example = Konnect.GetControlPlane.Invoke(new()
        ///     {
        ///         Name = "TestControlPlane",
        ///     });
        /// 
        /// });
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Output<GetControlPlaneResult> Invoke(GetControlPlaneInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetControlPlaneResult>("konnect:index/getControlPlane:getControlPlane", args ?? new GetControlPlaneInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetControlPlaneArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// **(Optional, String)** The filter string to apply to the name of the control plane. Uses equality.
        /// </summary>
        [Input("name")]
        public string? Name { get; set; }

        /// <summary>
        /// **(Optional, String)** The search string to apply to the name of the control plane. Uses contains.
        /// </summary>
        [Input("searchName")]
        public string? SearchName { get; set; }

        public GetControlPlaneArgs()
        {
        }
        public static new GetControlPlaneArgs Empty => new GetControlPlaneArgs();
    }

    public sealed class GetControlPlaneInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// **(Optional, String)** The filter string to apply to the name of the control plane. Uses equality.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// **(Optional, String)** The search string to apply to the name of the control plane. Uses contains.
        /// </summary>
        [Input("searchName")]
        public Input<string>? SearchName { get; set; }

        public GetControlPlaneInvokeArgs()
        {
        }
        public static new GetControlPlaneInvokeArgs Empty => new GetControlPlaneInvokeArgs();
    }


    [OutputType]
    public sealed class GetControlPlaneResult
    {
        /// <summary>
        /// **(String)** The cluster type of the control plane.
        /// </summary>
        public readonly string ClusterType;
        /// <summary>
        /// **(String)** The control plane endpoint URL of the control plane.
        /// </summary>
        public readonly string ControlPlaneEndpoint;
        /// <summary>
        /// **(String)** The description of the control plane.
        /// </summary>
        public readonly string Description;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string? Name;
        public readonly string? SearchName;
        /// <summary>
        /// **(String)** The telemetry endpoint URL of the control plane.
        /// </summary>
        public readonly string TelemetryEndpoint;

        [OutputConstructor]
        private GetControlPlaneResult(
            string clusterType,

            string controlPlaneEndpoint,

            string description,

            string id,

            string? name,

            string? searchName,

            string telemetryEndpoint)
        {
            ClusterType = clusterType;
            ControlPlaneEndpoint = controlPlaneEndpoint;
            Description = description;
            Id = id;
            Name = name;
            SearchName = searchName;
            TelemetryEndpoint = telemetryEndpoint;
        }
    }
}
