// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Represents an HMAC credential for a consumer within a control plane
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as konnect from "@camsechrist/pulumi-konnect";
 * import * as konnect from "@pulumi/konnect";
 *
 * const controlPlane = konnect.getControlPlane({
 *     name: "TestControlPlane",
 * });
 * const consumer = controlPlane.then(controlPlane => konnect.getConsumer({
 *     controlPlaneId: controlPlane.id,
 *     searchUsername: "Bob",
 * }));
 * const example = new konnect.ConsumerHMAC("example", {
 *     controlPlaneId: controlPlane.then(controlPlane => controlPlane.id),
 *     consumerId: consumer.then(consumer => consumer.consumerId),
 *     username: "my-username",
 *     secret: "my-secret",
 * });
 * ```
 *
 * ## Import
 *
 * Consumer HMACs can be imported using a proper value of `id` as described above
 */
export class ConsumerHMAC extends pulumi.CustomResource {
    /**
     * Get an existing ConsumerHMAC resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ConsumerHMACState, opts?: pulumi.CustomResourceOptions): ConsumerHMAC {
        return new ConsumerHMAC(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'konnect:index/consumerHMAC:ConsumerHMAC';

    /**
     * Returns true if the given object is an instance of ConsumerHMAC.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ConsumerHMAC {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ConsumerHMAC.__pulumiType;
    }

    /**
     * **(Required, String)** The id of the consumer.
     */
    public readonly consumerId!: pulumi.Output<string>;
    /**
     * **(Required, String)** The id of the control plane.
     */
    public readonly controlPlaneId!: pulumi.Output<string>;
    /**
     * **(String)** Id of the consumer HMAC alone
     */
    public /*out*/ readonly hmacId!: pulumi.Output<string>;
    /**
     * **(Optional/Computed, String)** The secret value.  If left out, a secret will be generated for you.
     */
    public readonly secret!: pulumi.Output<string>;
    /**
     * **(Required, String)** The username value.
     */
    public readonly username!: pulumi.Output<string>;

    /**
     * Create a ConsumerHMAC resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ConsumerHMACArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ConsumerHMACArgs | ConsumerHMACState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ConsumerHMACState | undefined;
            resourceInputs["consumerId"] = state ? state.consumerId : undefined;
            resourceInputs["controlPlaneId"] = state ? state.controlPlaneId : undefined;
            resourceInputs["hmacId"] = state ? state.hmacId : undefined;
            resourceInputs["secret"] = state ? state.secret : undefined;
            resourceInputs["username"] = state ? state.username : undefined;
        } else {
            const args = argsOrState as ConsumerHMACArgs | undefined;
            if ((!args || args.consumerId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'consumerId'");
            }
            if ((!args || args.controlPlaneId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'controlPlaneId'");
            }
            if ((!args || args.username === undefined) && !opts.urn) {
                throw new Error("Missing required property 'username'");
            }
            resourceInputs["consumerId"] = args ? args.consumerId : undefined;
            resourceInputs["controlPlaneId"] = args ? args.controlPlaneId : undefined;
            resourceInputs["secret"] = args ? args.secret : undefined;
            resourceInputs["username"] = args ? args.username : undefined;
            resourceInputs["hmacId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ConsumerHMAC.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ConsumerHMAC resources.
 */
export interface ConsumerHMACState {
    /**
     * **(Required, String)** The id of the consumer.
     */
    consumerId?: pulumi.Input<string>;
    /**
     * **(Required, String)** The id of the control plane.
     */
    controlPlaneId?: pulumi.Input<string>;
    /**
     * **(String)** Id of the consumer HMAC alone
     */
    hmacId?: pulumi.Input<string>;
    /**
     * **(Optional/Computed, String)** The secret value.  If left out, a secret will be generated for you.
     */
    secret?: pulumi.Input<string>;
    /**
     * **(Required, String)** The username value.
     */
    username?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a ConsumerHMAC resource.
 */
export interface ConsumerHMACArgs {
    /**
     * **(Required, String)** The id of the consumer.
     */
    consumerId: pulumi.Input<string>;
    /**
     * **(Required, String)** The id of the control plane.
     */
    controlPlaneId: pulumi.Input<string>;
    /**
     * **(Optional/Computed, String)** The secret value.  If left out, a secret will be generated for you.
     */
    secret?: pulumi.Input<string>;
    /**
     * **(Required, String)** The username value.
     */
    username: pulumi.Input<string>;
}
