// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Represents an API key credential for a consumer within a control plane
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as konnect from "@camsechrist/pulumi-konnect";
 * import * as konnect from "@pulumi/konnect";
 *
 * const controlPlane = konnect.getControlPlane({
 *     name: "TestControlPlane",
 * });
 * const consumer = controlPlane.then(controlPlane => konnect.getConsumer({
 *     controlPlaneId: controlPlane.id,
 *     searchUsername: "Bob",
 * }));
 * const example = new konnect.ConsumerKey("example", {
 *     controlPlaneId: controlPlane.then(controlPlane => controlPlane.id),
 *     consumerId: consumer.then(consumer => consumer.consumerId),
 *     key: "my-api-key",
 * });
 * ```
 *
 * ## Import
 *
 * Consumer keys can be imported using a proper value of `id` as described above
 */
export class ConsumerKey extends pulumi.CustomResource {
    /**
     * Get an existing ConsumerKey resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ConsumerKeyState, opts?: pulumi.CustomResourceOptions): ConsumerKey {
        return new ConsumerKey(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'konnect:index/consumerKey:ConsumerKey';

    /**
     * Returns true if the given object is an instance of ConsumerKey.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ConsumerKey {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ConsumerKey.__pulumiType;
    }

    /**
     * **(Required, String)** The id of the consumer.
     */
    public readonly consumerId!: pulumi.Output<string>;
    /**
     * **(Required, String)** The id of the control plane.
     */
    public readonly controlPlaneId!: pulumi.Output<string>;
    /**
     * **(Optional/Computed, String)** The API key value.  If left out, a key will be generated for you.
     */
    public readonly key!: pulumi.Output<string>;
    /**
     * **(String)** Id of the consumer API key alone
     */
    public /*out*/ readonly keyId!: pulumi.Output<string>;

    /**
     * Create a ConsumerKey resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ConsumerKeyArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ConsumerKeyArgs | ConsumerKeyState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ConsumerKeyState | undefined;
            resourceInputs["consumerId"] = state ? state.consumerId : undefined;
            resourceInputs["controlPlaneId"] = state ? state.controlPlaneId : undefined;
            resourceInputs["key"] = state ? state.key : undefined;
            resourceInputs["keyId"] = state ? state.keyId : undefined;
        } else {
            const args = argsOrState as ConsumerKeyArgs | undefined;
            if ((!args || args.consumerId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'consumerId'");
            }
            if ((!args || args.controlPlaneId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'controlPlaneId'");
            }
            resourceInputs["consumerId"] = args ? args.consumerId : undefined;
            resourceInputs["controlPlaneId"] = args ? args.controlPlaneId : undefined;
            resourceInputs["key"] = args ? args.key : undefined;
            resourceInputs["keyId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ConsumerKey.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ConsumerKey resources.
 */
export interface ConsumerKeyState {
    /**
     * **(Required, String)** The id of the consumer.
     */
    consumerId?: pulumi.Input<string>;
    /**
     * **(Required, String)** The id of the control plane.
     */
    controlPlaneId?: pulumi.Input<string>;
    /**
     * **(Optional/Computed, String)** The API key value.  If left out, a key will be generated for you.
     */
    key?: pulumi.Input<string>;
    /**
     * **(String)** Id of the consumer API key alone
     */
    keyId?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a ConsumerKey resource.
 */
export interface ConsumerKeyArgs {
    /**
     * **(Required, String)** The id of the consumer.
     */
    consumerId: pulumi.Input<string>;
    /**
     * **(Required, String)** The id of the control plane.
     */
    controlPlaneId: pulumi.Input<string>;
    /**
     * **(Optional/Computed, String)** The API key value.  If left out, a key will be generated for you.
     */
    key?: pulumi.Input<string>;
}
