// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Represents an ACL credential for a consumer within a control plane
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as konnect from "@camsechrist/pulumi-konnect";
 * import * as konnect from "@pulumi/konnect";
 *
 * const controlPlane = konnect.getControlPlane({
 *     name: "TestControlPlane",
 * });
 * const consumer = controlPlane.then(controlPlane => konnect.getConsumer({
 *     controlPlaneId: controlPlane.id,
 *     searchUsername: "Bob",
 * }));
 * const example = new konnect.ConsumerACL("example", {
 *     controlPlaneId: controlPlane.then(controlPlane => controlPlane.id),
 *     consumerId: consumer.then(consumer => consumer.consumerId),
 *     group: "my-acl-group",
 * });
 * ```
 *
 * ## Import
 *
 * Consumer ACLs can be imported using a proper value of `id` as described above
 */
export class ConsumerACL extends pulumi.CustomResource {
    /**
     * Get an existing ConsumerACL resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ConsumerACLState, opts?: pulumi.CustomResourceOptions): ConsumerACL {
        return new ConsumerACL(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'konnect:index/consumerACL:ConsumerACL';

    /**
     * Returns true if the given object is an instance of ConsumerACL.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ConsumerACL {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ConsumerACL.__pulumiType;
    }

    /**
     * **(String)** Id of the consumer ACL alone
     */
    public /*out*/ readonly aclId!: pulumi.Output<string>;
    /**
     * **(Required, String)** The id of the consumer.
     */
    public readonly consumerId!: pulumi.Output<string>;
    /**
     * **(Required, String)** The id of the control plane.
     */
    public readonly controlPlaneId!: pulumi.Output<string>;
    /**
     * **(Required, String)** The ACL group value.
     */
    public readonly group!: pulumi.Output<string>;

    /**
     * Create a ConsumerACL resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ConsumerACLArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ConsumerACLArgs | ConsumerACLState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ConsumerACLState | undefined;
            resourceInputs["aclId"] = state ? state.aclId : undefined;
            resourceInputs["consumerId"] = state ? state.consumerId : undefined;
            resourceInputs["controlPlaneId"] = state ? state.controlPlaneId : undefined;
            resourceInputs["group"] = state ? state.group : undefined;
        } else {
            const args = argsOrState as ConsumerACLArgs | undefined;
            if ((!args || args.consumerId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'consumerId'");
            }
            if ((!args || args.controlPlaneId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'controlPlaneId'");
            }
            if ((!args || args.group === undefined) && !opts.urn) {
                throw new Error("Missing required property 'group'");
            }
            resourceInputs["consumerId"] = args ? args.consumerId : undefined;
            resourceInputs["controlPlaneId"] = args ? args.controlPlaneId : undefined;
            resourceInputs["group"] = args ? args.group : undefined;
            resourceInputs["aclId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ConsumerACL.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ConsumerACL resources.
 */
export interface ConsumerACLState {
    /**
     * **(String)** Id of the consumer ACL alone
     */
    aclId?: pulumi.Input<string>;
    /**
     * **(Required, String)** The id of the consumer.
     */
    consumerId?: pulumi.Input<string>;
    /**
     * **(Required, String)** The id of the control plane.
     */
    controlPlaneId?: pulumi.Input<string>;
    /**
     * **(Required, String)** The ACL group value.
     */
    group?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a ConsumerACL resource.
 */
export interface ConsumerACLArgs {
    /**
     * **(Required, String)** The id of the consumer.
     */
    consumerId: pulumi.Input<string>;
    /**
     * **(Required, String)** The id of the control plane.
     */
    controlPlaneId: pulumi.Input<string>;
    /**
     * **(Required, String)** The ACL group value.
     */
    group: pulumi.Input<string>;
}
