// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Represents a control plane
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as konnect from "@camsechrist/pulumi-konnect";
 *
 * const example = new konnect.ControlPlane("example", {description: "TestControlPlane"});
 * ```
 *
 * ## Import
 *
 * Control planes can be imported using a proper value of `id` as described above
 */
export class ControlPlane extends pulumi.CustomResource {
    /**
     * Get an existing ControlPlane resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ControlPlaneState, opts?: pulumi.CustomResourceOptions): ControlPlane {
        return new ControlPlane(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'konnect:index/controlPlane:ControlPlane';

    /**
     * Returns true if the given object is an instance of ControlPlane.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ControlPlane {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ControlPlane.__pulumiType;
    }

    /**
     * **(String)** The cluster type of the control plane.
     */
    public /*out*/ readonly clusterType!: pulumi.Output<string>;
    /**
     * **(String)** The control plane endpoint URL of the control plane.
     */
    public /*out*/ readonly controlPlaneEndpoint!: pulumi.Output<string>;
    /**
     * **(Optional, String)** The description of the control plane.
     */
    public readonly description!: pulumi.Output<string | undefined>;
    /**
     * **(Required, String)** The name of the control plane.
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * **(String)** The telemetry endpoint URL of the control plane.
     */
    public /*out*/ readonly telemetryEndpoint!: pulumi.Output<string>;

    /**
     * Create a ControlPlane resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: ControlPlaneArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ControlPlaneArgs | ControlPlaneState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ControlPlaneState | undefined;
            resourceInputs["clusterType"] = state ? state.clusterType : undefined;
            resourceInputs["controlPlaneEndpoint"] = state ? state.controlPlaneEndpoint : undefined;
            resourceInputs["description"] = state ? state.description : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["telemetryEndpoint"] = state ? state.telemetryEndpoint : undefined;
        } else {
            const args = argsOrState as ControlPlaneArgs | undefined;
            resourceInputs["description"] = args ? args.description : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["clusterType"] = undefined /*out*/;
            resourceInputs["controlPlaneEndpoint"] = undefined /*out*/;
            resourceInputs["telemetryEndpoint"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ControlPlane.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ControlPlane resources.
 */
export interface ControlPlaneState {
    /**
     * **(String)** The cluster type of the control plane.
     */
    clusterType?: pulumi.Input<string>;
    /**
     * **(String)** The control plane endpoint URL of the control plane.
     */
    controlPlaneEndpoint?: pulumi.Input<string>;
    /**
     * **(Optional, String)** The description of the control plane.
     */
    description?: pulumi.Input<string>;
    /**
     * **(Required, String)** The name of the control plane.
     */
    name?: pulumi.Input<string>;
    /**
     * **(String)** The telemetry endpoint URL of the control plane.
     */
    telemetryEndpoint?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a ControlPlane resource.
 */
export interface ControlPlaneArgs {
    /**
     * **(Optional, String)** The description of the control plane.
     */
    description?: pulumi.Input<string>;
    /**
     * **(Required, String)** The name of the control plane.
     */
    name?: pulumi.Input<string>;
}
