// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Represents a control plane
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as konnect from "@pulumi/konnect";
 *
 * const example = konnect.getControlPlane({
 *     name: "TestControlPlane",
 * });
 * ```
 */
export function getControlPlane(args?: GetControlPlaneArgs, opts?: pulumi.InvokeOptions): Promise<GetControlPlaneResult> {
    args = args || {};

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("konnect:index/getControlPlane:getControlPlane", {
        "name": args.name,
        "searchName": args.searchName,
    }, opts);
}

/**
 * A collection of arguments for invoking getControlPlane.
 */
export interface GetControlPlaneArgs {
    /**
     * **(Optional, String)** The filter string to apply to the name of the control plane. Uses equality.
     */
    name?: string;
    /**
     * **(Optional, String)** The search string to apply to the name of the control plane. Uses contains.
     */
    searchName?: string;
}

/**
 * A collection of values returned by getControlPlane.
 */
export interface GetControlPlaneResult {
    /**
     * **(String)** The cluster type of the control plane.
     */
    readonly clusterType: string;
    /**
     * **(String)** The control plane endpoint URL of the control plane.
     */
    readonly controlPlaneEndpoint: string;
    /**
     * **(String)** The description of the control plane.
     */
    readonly description: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name?: string;
    readonly searchName?: string;
    /**
     * **(String)** The telemetry endpoint URL of the control plane.
     */
    readonly telemetryEndpoint: string;
}
/**
 * Represents a control plane
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as konnect from "@pulumi/konnect";
 *
 * const example = konnect.getControlPlane({
 *     name: "TestControlPlane",
 * });
 * ```
 */
export function getControlPlaneOutput(args?: GetControlPlaneOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetControlPlaneResult> {
    return pulumi.output(args).apply((a: any) => getControlPlane(a, opts))
}

/**
 * A collection of arguments for invoking getControlPlane.
 */
export interface GetControlPlaneOutputArgs {
    /**
     * **(Optional, String)** The filter string to apply to the name of the control plane. Uses equality.
     */
    name?: pulumi.Input<string>;
    /**
     * **(Optional, String)** The search string to apply to the name of the control plane. Uses contains.
     */
    searchName?: pulumi.Input<string>;
}
